version: 0.2

phases:
  install:
    commands:
      - echo Entered the install phase...
      - ls
      - aws deploy push --application-name Test --s3-location s3://codedeploy-artifacts-me-south-1-926940654199/Test/DeployArtif/test.zip
