version: 0.2

phases:
  install:
    commands:
      - echo Entered the install phase...
      - ls
      - zip test.zip *
      - ls
      - aws s3 cp test.zip s3://codedeploy-artifacts-me-south-1-926940654199/Test/DeployArtif/test.zip
      - aws s3 cp s3://codedeploy-artifacts-me-south-1-926940654199/Test/DeployArtif/test.zip s3://aws-codedeploy-artifacts-me-south-1-926940654199/Test/DeployArtif/test.zip
      - aws deploy push --application-name Test --s3-location s3://codedeploy-artifacts-me-south-1-926940654199/Test/DeployArtif/test.zip
