version: 0.2

phases:
  install:
    commands:
      - echo Entered the install phase...
      - ls
      - zip test.zip *
      - ls
      - aws s3 cp test.zip s3://codedeploy-artifacts-me-south-1-926940654199/Test/DeployArtif/test.zip
